apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbkBzaG9haWJjbHVzdGVyLmR6eGhoMGoubW9uZ29kYi5uZXQvYmxvZ19wcm9qZWN0P3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  IP_ADDRESS: My4yMTEuNjYuMg==