---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-frontend
  template:
    metadata:
      labels:
        app: blog-frontend
    spec:
      containers:
        - name: blog-frontend
          image: shoaibisone/open-blog:frontend-latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MONGODB_URI
            - name: IP_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: IP_ADDRESS