name: CI/CD for Open Blog App

on:
    push:
        branches:
            - main
            - master

env:
    MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: List current directory contents
        run: ls -al

      # Backend Build and Push
      - name: Build and push Backend Docker image
        run: |
          cd blog-backend
          docker build -t shoaibisone/open-blog:backend-latest .
          docker push shoaibisone/open-blog:backend-latest

      # Frontend Build and Push
      - name: Build and push Frontend Docker image
        run: |
          cd blog-frontend
          docker build -t shoaibisone/open-blog:frontend-latest .
          docker push shoaibisone/open-blog:frontend-latest

      # Deploy to Kubernetes
      - name: SSH to AWS Instance and Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.AWS_INSTANCE_IP }}  
          REMOTE_USER: minikube-user 
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
          SCRIPT_BEFORE: |
            whoami
            ls -al
            # Create a directory for Kubernetes YAML files
            mkdir -p /home/minikube-user/Blog_Project/kubernetes

            cd /home/minikube-user/Blog_Project/kubernetes

            # Copy YAML files from GitHub Actions runner to the AWS instance
            curl -O https://github.com/shoaibalisabir/open-blogging/blob/master/kubernetes/backend-deployment.yaml
            curl -O https://github.com/shoaibalisabir/open-blogging/blob/master/kubernetes/frontend-deployment.yaml

            kubectl apply -f /home/minikube-user/Blog_Project/kubernetes/backend-deployment.yaml
            kubectl apply -f /home/minikube-user/Blog_Project/kubernetes/frontend-deployment.yaml
